AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''
Parameters:
  RoleArn:
    Type: String
  S3Bucket:
    Type: String
  S3Prefix:
    Type: String
  S3Region:
    Type: String
  SqsURL:
    Type: String
  SecretArn:
    Type: String
  FalconRegion:
    Type: String

Resources:
  SqsReceiver:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: main
      Runtime: go1.x
      Timeout: 300
      MemorySize: 1024
      Role:
        Ref: RoleArn
      Environment:
        Variables:
          S3_BUCKET:
            Ref: S3Bucket
          S3_PREFIX:
            Ref: S3Prefix
          S3_REGION:
            Ref: S3Region
          SQS_URL:
            Ref: SqsURL
          SECRET_ARN:
            Ref: SecretArn
          FALCON_REGION:
            Ref: FalconRegion
      Events:
        EveryMinutes:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
